version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "training-distribute-code-app"
s3_prefix = "training-distribute-code-app"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
